### PR TITLE
logo added

### PR DESCRIPTION
**Pull request by reallinfo**

### CODE REVIEW

**Comment by jedie** [comment]
Really cool. But can you upload the image as svg ?

**Comment by reallinfo** [comment]
Sure, is it OK?

**Comment by jedie** [comment]
Thanks!

I think i will only add the green one ;)

@reallinfo can you provide licence and copyright information ?

**Comment by reallinfo** [comment]
the logo is licensed under a Creative Commons Attribution 4.0 International License

https://creativecommons.org/licenses/by/4.0/

**Comment by reallinfo** [comment]
Is there any problem in pull request?

**Comment by jedie** [comment]
Sorry for late response... I added the logo now in README.

Thank you for contribution.

**Pull request merged**
